services:

  metabase:
    image: metabase/metabase:v0.55.4
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${MB_DBNAME}
      MB_DB_PORT: 5432
      MB_DB_USER_FILE: /run/secrets/db_user
      MB_DB_PASS_FILE: /run/secrets/db_password
      MB_DB_HOST: postgres
      MB_ENCRYPTION_SECRET_KEY: /run/secrets/mb_key
    networks:
      - metanet1
    depends_on:
      - postgres
    secrets:
      - db_password
      - db_user
      - mb_key
    restart: always

  postgres:
    image: postgres:15.13
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: ${MB_DBNAME}
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - metanet1
    secrets:
      - db_password
      - db_user
    restart: always

networks:
  metanet1:
    driver: bridge

secrets:
  db_password:
    file: db_password.txt
  db_user:
    file: db_user.txt
  mb_key:
    file: mb_key.txt
